config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end    
  end

  resources :posts, only: [:create, :edit, :update, :destroy]
  resources :activities, only: [:index]

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
include PublicActivity::Model
	
	belongs_to :user
	belongs_to :friend, class_name: "User"


	def accept_friendship
		self.update_attributes(state: "active", friended_at: Time.now)
	end

	def deny_friendship
		self.destroy
	end

	def cancel_friendship
		self.destroy 
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
	include PublicActivity::Model
	belongs_to :user
	validates_presence_of :user_id
	validates_presence_of :content

	auto_html_for :content do
		html_escape
		image
		youtube(width: "100%", height: 250, autoplay: false)
		link target: "_blank", rel: "nofollow"
		simple_format
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :posts, dependent: :destroy

  def request_friendship(user_2)
  	self.friendships.create(friend: user_2)
  end

  def pending_friend_requests_from
    self.inverse_friendships.where(state: "pending")
  end

  def pending_friend_requests_to
    self.friendships.where(state: "pending")
  end
  
  def active_friends
    self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:user)
  end  

  def friendship_status(user_2)
    friendship = Friendship.where(user_id: [self.id, user_2.id], friend_id: [self.id, user_2.id])
    unless friendship.any? 
      return "not_friends"
    else 
      if friendship.first.state == "active"
        return "friends"
      else
        if friendship.first.user == self
          return "pending"
        else
          return "requested"
        end
      end
    end
  end

  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id, user_2.id], friend_id: [self.id, user_2.id]).first 
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :authenticate_user!, only: [:index]

	def index
		@users = current_user.active_friends
		@users.push(current_user)
		case params[:content] when 'posts'
			@activities = PublicActivity::Activity.where(owner_id: @users, trackable_type: "Post").order('created_at DESC')
		else
			@activities = PublicActivity::Activity.where(owner_id: @users).order('created_at DESC')
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :request_count
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	def request_count
		current_user.pending_friend_requests_from.map(&:user).size  	
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, only: [:create]
	before_action :set_friendship, only: [:destroy, :accept]

	def create
		@friendship = current_user.request_friendship(@user)
		respond_to do |format|
			format.html {redirect_to users_path, notice: "Friendship Created"}
		end
	end

	def destroy
		@friendship.destroy
		respond_to do |format|
			format.html {redirect_to users_path, notice: "Friendship Deleted"}
		end
	end

	def accept
		@friendship.accept_friendship
		@friendship.create_activity key: 'friendship.accepted', owner: @friendship.user, recipient: @friendship.friend
		@friendship.create_activity key: 'friendship.accepted', owner: @friendship.friend, recipient: @friendship.user
		respond_to do |format|
			format.html {redirect_to users_path, notice: "Friendship Accepted"}
		end
	end

	private

	def set_user
		@user = User.find(params[:user_id])
	end

	def set_friendship
		@friendship = Friendship.find(params[:id])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if current_user
  		redirect_to activities_path
	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:edit, :update, :destroy]

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			@post.create_activity key: 'post.created', owner: @post.user
			respond_to do |format|
				format.html { redirect_to user_path(@post.user.username), notice: "Post created!" }
			end
		else
			redirect_to user_path(@post.user.username), notice: "Something went wrong!"
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			respond_to do |format|
				format.html { redirect_to user_path(@post.user.username), notice: "Post updated!" }
			end
		else
			redirect_to post_path(@post), notice: "Something went wrong!"
		end
	end

	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to user_path(@post.user.username), notice: "Post Removed!" }
		end
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:content)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username)
	end

	def account_update_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username, :current_password, :bio, :age, :gender)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_action :authenticate_user!, only: [:index]
   before_action :set_user, only: [:show]
   before_action :get_counts, only: [:index]

  def index
    case params[:people]
    when "friends"
      @users = current_user.active_friends
    when "requests"
      @users = current_user.pending_friend_requests_from.map(&:user)
    when "pending"
      @users = current_user.pending_friend_requests_to.map(&:friend)
    else
      @users = User.where.not(id: current_user.id)
    end
  end

  def show
    @post = Post.new
    @posts = @user.posts.order('created_at DESC')
    @activities = PublicActivity::Activity.where(owner_id: @user.id).order('created_at DESC')
  end

  private

  def get_counts
    @friend_count = current_user.active_friends.size
    @pending_count = current_user.pending_friend_requests_to.map(&:friend).size
  end

  def set_user
  	@user = User.find_by(username: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def action_buttons(user)
		case current_user.friendship_status(user) when "friends"
			link_to "Cancel Friendship", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "pending"
			link_to "Cancel Request", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "requested"
			#"Accept or Deny"
			link_to "Accept", accept_friendship_path(current_user.friendship_relation(user)), method: :put			
		when "not_friends"
			link_to "Add as Friend", friendships_path(user_id: user.id), method: :post
		end
	end

end

app/views/activities/index.html.erb
<div class="jumbotron text-center">
	<h1>Timeline</h1>
	<div class="btn-group" role="group" aria-label="Default">
		<%= link_to "Everything", activities_path, class: "btn btn-default #{'active' unless params[:content]}" %>
		<%= link_to "Just Posts", activities_path(content: "posts"), class: "btn btn-default #{'active' if params[:content] == 'posts'}" %>
	</div>
</div>

<div class="container">
	<ul class="timeline">
		
		<% @activities.each_with_index do |activity| %>
			<% unless activity.trackable_type == "Friendship" && activity.owner == current_user %>
			<% if activity.trackable %>
				<% if cycle('odd', 'even') == 'odd' %>
					<li class="timeline-inverted">
				<% else %>
					<li>
				<% end %>
				<div class="timeline-badge"><%= gravatar_tag activity.owner.email, size: 55 %></div>
				<div class="timeline-panel">				
					<div class="timeline-heading">
						<h4 class="timeline-title"><%= link_to activity.owner.username, user_path(activity.owner.username) %></h4>
						<p><small><%= time_ago_in_words(activity.created_at) %></small></p>
					</div>
					<div class="timeline-body">
						<% case activity.trackable_type when "Post" %>
						<p><%= raw(activity.trackable.content_html) %>
						<% when "Friendship" %>
						<%= link_to activity.owner.username, user_path(activity.owner.username) %> is now friends with <%=link_to activity.recipient.username, user_path(activity.recipient.username) %>
						<% end %>
					</div>
				</div>
					
			<% end %>
			<% end %>
		<% end %>
	</ul>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Penthouse Junction", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>        
        <li><%= link_to "Timeline", activities_path %></li>
        <li><%= link_to "People (#{request_count})", users_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %> <%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", user_path(current_user.username) %></li>
            <li><%= link_to "Friends", users_path(people: "friends") %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Penthouse Junction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<% flash.each do |type, message | %>
	<div class="alert alert-info fade-in">
		<button class="close" data-dismiss="alert">x</button>
		<%= message %>
	</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="landing">
	<div class="container">
		<div class="row text-center">
			<div class="jumbotron front-title">
				<h1>Welcome to Penthouse Junction</h1>
				<h3>A place where Social meets Luxury</h3>
				<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
			</div>
		</div>
	</div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<div class="panel panel-info">
	<div class="panel-heading">Post</div>
	<div class="panel-body">
		<%= f.error_notification %>
		<%= f.input :content, required: true, label: false, placeholder: "New Post Content Here", input_html: {class: "form-control"} %>
	</div>
	<div class="panel-footer">
		<%= f.button :submit, class: "btn btn-primary btn-block" %>
	</div>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<%= gravatar_tag post.user.email, size:20 %>  <%= post.user.username %> posted this about <%= time_ago_in_words(post.created_at) %> ago 
		<% if current_user && current_user == post.user %>
		<%= link_to "edit", edit_post_path(post) %> | <%= link_to "x", post_path(post), method: :delete %>
		<% end %>
	</div>
	<div class="panel-body">
		<%= raw(post.content_html) %>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<%= render "form" %>
</div>

app/views/public_activity/friendship/_accepted.html.erb
<% if activity.trackable %>
<p><%= link_to activity.owner.username, user_path(activity.owner.username) %> is now friends with <%= link_to activity.recipient.username, user_path(activity.recipient.username) %></p>
<% end %>

app/views/public_activity/post/_created.html.erb
<% if activity.trackable %>
<p><%= link_to activity.owner.username, user_path(activity.owner.username) %> posted something <%= time_ago_in_words(activity.created_at) %> ago</p>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-3">
	<div class="thumbnail">
		<%= link_to user_path(user.username) do %>
			<%= gravatar_tag user.email, size: 200 %>
		<% end %>
		<div class="caption">
			<h3><%= user.username %></h3>
			<% if current_user %>
			<p><%= action_buttons(user) %></p>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="jumbotron text-center">
	<h2>People</h2>
	<div class="btn-group" role="group" aria-label="Default Button Groups" >
		<%= link_to "Everyone", users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
		<%= link_to "Friends (#{@friend_count})", users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == 'friends'}" %>
		<%= link_to "Requests (#{request_count})", users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == 'requests'}" %>
		<%= link_to "Pending (#{@pending_count})", users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == 'pending'}" %>
	</div>
</div>

<div class="container">
	<div class="row">
		<%= render @users %>
	</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="row">
			
			<div class="col-md-4">
				<%= gravatar_tag @user.email, size: 200 %>
			</div>

			<div class="col-md-4">
				<h3><%= @user.username %></h3>
				<p>Age: <%= @user.age %></p>
				<p>Gender: <%= @user.gender %></p>
			</div>
			<div class="col-md-4">
				<h3>Who Am I</h3>
				<small><%= @user.bio %></small>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<!-- Friend Zone -->
		<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				Friends (<%= @user.active_friends.size %>)
			</div>
			<div class="panel-body">
				<% @user.active_friends.last(16).each do |user| %> 
					<%= link_to user_path(user.username) do %>
						<%= gravatar_tag user.email, size: 40 %>
					<% end %>
				<% end %>
			</div>
		</div>
		</div>
		<!-- Profile Zone -->
		<div class="col-md-6">
		<% if current_user && current_user == @user %>
		<%= render "posts/form" %>
		<% end %>
		<%= render @posts %>
		</div>
		<!-- Profile Activity -->		
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">Recent Activity</div>
				<div class="panel-body">
					<%= render_activities(@activities) %>
				</div>
			</div>
		</div>
	</div>
</div>